#!/bin/sh


cd "$HOME/Music"


file="$(find -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Music:')"
[ -z "$file" ] && exit


#st -e mpv "$file" &
$(echo "ffplay\nst -e mpv\ndeadbeef\nchromium" | dmenu) "$file" &
