#!/bin/sh



PACKAGE="$(dpkg-query --show -f '${source:Package} ${source:Version}\n' | sort -s \
                                                                        | dmenu -i -p 'Package:' -l 8 \
                                                                        | awk '{ print $1 }')"
[ -z "$PACKAGE" ] && exit



#PACKAGE_COMMAND="apt show"

PACKAGE_COMMAND="$(echo 'apt show\ndpkg -L' | dmenu -l 2)"
[ -z "$PACKAGE_COMMAND" ] && exit



st -t "$PACKAGE" -e dash -c "$PACKAGE_COMMAND $PACKAGE; read -p ':' ''"  &
