#!/bin/sh


cd "$HOME/Pictures"


file="$(find -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Picture:')"
[ -z "$file" ] && exit


#feh "$file" &
$(echo "feh\nmirage\nmtpaint\nchromium" | dmenu) "$file" &
