#!/bin/sh



cd "$HOME/Documents"



DOCUMENT_FILE="$(find -type f -not -path '*/.*' | sort \
                                                | dmenu -i -l 8 -p 'Document:')"
[ -z "$DOCUMENT_FILE" ] && exit



DOCUMENT_VIEWER="$(echo 'chromium\nqpdfview\nzathura\nleafpad' | dmenu)"
[ -z "$DOCUMENT_VIEWER" ] && exit



$DOCUMENT_VIEWER "$DOCUMENT_FILE" &
