#!/bin/sh



cd "$HOME/Music"


# Prompt to select music
file="$(find -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Music:')"
[ -z "$file" ] && exit


## Set music player
#music_player="st -e mpv"

## Select music player
music_player="$(echo 'ffplay\nst -e mpv\ndeadbeef\nchromium' | dmenu)"
[ -z "$music_player" ] && exit



# Open in music player
$music_player "$file" &
