#!/bin/sh



cd "$HOME"



PROJECT="$(dmenu -i -l 8 -p 'Build:' < "$HOME/.config/dmenu/dmenu_build")"
[ -z "$PROJECT" ] && exit

cd "$PROJECT"

CMD="$(echo "make all -j2\nmake clean\nsudo make install" | dmenu -l 3)"
[ -z "$CMD" ] && exit



st -t "$PROJECT" -e dash -c "$CMD; read -p ':' ''"
