#!/bin/sh


cd "$HOME/Videos"


file="$(find -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Video:')"
[ -z "$file" ] && exit


#video_player="mpv"
video_player="$(echo 'mpv\nffplay\nchromium' | dmenu)"
[ -z "$video_player" ] && exit

$video_player "$file" &
