#!/bin/sh



CMD="$(dmenu_path | dmenu -l 8 -p '~>')"
[ -z "$CMD" ] && exit



st -t "$CMD" -e dash -c "$CMD; read -p ':' 'PROMPT'" &
#st -t "$CMD" -e dash -c "echo '$ $CMD'; $CMD; read -p ':' 'PROMPT'" &
