#!/bin/sh



cd "$HOME"



CONFIG_FILE="$(dmenu -i -l 8 -p 'Config:' < "$HOME/.config/dmenu/dmenu_config")"
[ -z "$CONFIG_FILE" ] && exit



#CONFIG_EDITOR="st -e nano"

CONFIG_EDITOR="$(echo 'st -e nano\nleafpad\ngeany' | dmenu)"
[ -z "$CONFIG_EDITOR" ] && exit



$CONFIG_EDITOR "$CONFIG_FILE" &
