#!/bin/sh


manpage=$(apropos . | sort | awk '{ print $1 " " $2 }' | dmenu -p 'Man:' -l 8)
#manpage=$(apropos . | dmenu -l 8 -p 'Man:' | awk '{ print $1 " " $2 }')

[ -z "$manpage" ] && exit


st -t "$manpage" -e man $manpage &
