#! /usr/bin/dash


cd /home/shivans/
file=$(cat /home/shivans/.config/dmenu/dmenu_config | dmenu -l 8 -p 'Config:')


case $file in "") exit;; esac


st -e nano "${file}" &
#st -e $(printf "vim\nnano" | dmenu) "${file}" &
