#!/bin/sh



cd "$HOME/Pictures"



PICTURE_FILE="$(find -type f -not -path '*/.*' | sort \
                                               | dmenu -i -l 8 -p 'Picture:')"
[ -z "$PICTURE_FILE" ] && exit



#PICTURE_VIEWER="feh"

PICTURE_VIEWER="$(echo "feh\n`
                       `mirage\n`
                       `mtpaint\n`
                       `chromium" | dmenu)"

[ -z "$PICTURE_VIEWER" ] && exit



$PICTURE_VIEWER "$PICTURE_FILE" &
