#! /usr/bin/dash



web=$(cat $HOME/.config/dmenu/dmenu_web-bookmarks | dmenu -i -l 8 -p 'Web:')
[ -z "$web" ] && exit


#chromium "$web" &
$(printf "chromium\nseamonkey\ndillo\nst -e elinks" | dmenu) "$web" &
