#!/bin/sh



package="$(dpkg-query --show -f '${source:Package} ${source:Version}\n' | sort -s | dmenu -i -p 'Package:' -l 8 | awk '{ print $1 }')"
[ -z "$package" ] && exit


#package_command="apt show"
package_command="$(echo 'apt show\ndpkg -L | less' | dmenu -l 2)"
[ -z "$package_command" ] && exit

st -t "$package" -e dash -c "$package_command $package ; read -p ':' ''"  &
