#!/bin/sh



WEB_URL="$(dmenu -i -l 8 -p 'Web:' < "$HOME/.config/dmenu/dmenu_web-bookmarks")"
[ -z "$WEB_URL" ] && exit



#WEB_BROWSER="chromium"

WEB_BROWSER="$(echo 'chromium\nseamonkey\ndillo\nst -e elinks' | dmenu)"
[ -z "$WEB_BROWSER" ] && exit



$WEB_BROWSER "$WEB_URL" &
