#!/bin/sh



# Prompt to set search
web_search="$(dmenu -p 'Web Search:')"
[ -z "$web_search" ] && exit

# Prompt to select search engine
search_engine="$(dmenu -i -l 8 -p 'Search in:' < "$HOME/.config/dmenu/dmenu_web-search")"
[ -z "$search_engine"] && exit

# Append search text and search engine url
web_search_url="$(echo "$search_engine" | awk -v web_search="$web_search" '{print $1 web_search $2}')"



## Set web browser
web_browser="chromium"

## Select web browser
#web_browser="$(printf 'chromium\nseamonkey\ndillo\nst -e elinks' | dmenu) 
[ -z "$web_browser" ] && exit



# Open in web browser
$web_browser "$web_search_url" &
