#!/bin/sh



cd "$HOME/Videos"



VIDEO_FILE="$(find -type f -not -path '*/.*' | sort \
                                             | dmenu -i -l 8 -p 'Video:')"
[ -z "$VIDEO_FILE" ] && exit



#VIDEO_PLAYER="mpv"

VIDEO_PLAYER="$(echo 'mpv\nffplay\nchromium' | dmenu)"
[ -z "$VIDEO_PLAYER" ] && exit



$VIDEO_PLAYER "$VIDEO_FILE" &
