#!/bin/sh


cd "$HOME/Pictures/Wallpapers"


wall="$(find ./ /usr/share/wallpaper/ -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Wallpaper:')"
[ -z "$wall" ] && exit


# feh
mode=$(echo "fill\nscale\nmax\ntile\ncenter" | dmenu)

# hsetroot
#mode=$(echo "fill\nfull\nextend\ntile\ncenter\ncover | dmenu)

[ -z "$mode" ] && exit


feh --bg-$mode "$wall" &
#hsetroot -$mode "$wall" &
