#!/bin/sh



WEB_SEARCH="$(dmenu -p 'Web Search:')"
[ -z "$WEB_SEARCH" ] && exit

SEARCH_ENGINE="$(dmenu -i -l 8 -p 'Search in:' < "$HOME/.config/dmenu/dmenu_web-search")"
[ -z "$SEARCH_ENGINE" ] && exit

WEB_SEARCH_URL="$(echo "$SEARCH_ENGINE" | awk -v SEARCH="$WEB_SEARCH" '{print $1 SEARCH $2}')"



#WEB_BROWSER="chromium"

WEB_BROWSER="$(echo "chromium\n`
                    `seamonkey\n`
                    `dillo\n`
                    `st -e elinks" | dmenu)"

[ -z "$WEB_BROWSER" ] && exit



$WEB_BROWSER "$WEB_SEARCH_URL" &
