#!/bin/sh


cd "$HOME/Music"


file="$(find -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Music:')"
[ -z "$file" ] && exit


#music_player="st -e mpv"
music_player="$(echo 'ffplay\nst -e mpv\ndeadbeef\nchromium' | dmenu)"
[ -z "$music_player" ] && exit

$music_player "$file" &
