#!/bin/sh



cd "$HOME/Documents"


# Prompt to select document
file="$(find -type f -not -path '*/.*' | sort | dmenu -i -l 8 -p 'Document:')"
[ -z "$file" ] && exit


# Select document viewer
document_viewer="$(echo 'chromium\nqpdfview\nzathura\nleafpad' | dmenu)"
[ -z "$document_viewer" ] && exit



# Open in document viewer
$document_viewer "$file" &
