#!/bin/sh


cd "$HOME"


project="$(dmenu -i -l 8 -p 'Build:' < "$HOME/.config/dmenu/dmenu_build")"
[ -z "$project" ] && exit


cd "$project"


cmd="$(echo "make all -j2\nmake clean\nsudo make install" | dmenu -l 3)"
[ -z "$cmd" ] && exit


st -t "$project" -e dash -c "$cmd; read -p ':' ''"
